### ISSUE TITLE
Lizardman Canyon Colisions out of date

### ISSUE THREAD

**Issue by SkrrtNick** [itsdax/Runescape-Web-Walker-Engine#107]
Is possible to get the lizardman canyon colisions updated? Explv's map is out of date, but beyond that walking to the canyon is a bit broken.

There's also the shortcut to it which makes it quite quick to get to the bank from. Happy to do as much as I can for this.

**Comment by FALSkills** [comment]
Can you please be as specific as possible with what needs to be remapped?  Maybe show an example of the path that your account would take where it can experience these problems.

**Comment by FALSkills** [comment]
I remapped this area today, pending a deployment by dax.
![image](https://user-images.githubusercontent.com/19998195/154764925-21c54392-351d-497a-8d5f-4b34d596d22c.png)

**Comment by SkrrtNick** [comment]
Hard when I don't have explv's but blue area won't create a path. Red area is shortcut that isn't mapped. Black area is inconsistent in that it will navigate through the gates in a weird way.

![image](https://user-images.githubusercontent.com/79165336/154765279-c4c14d93-8009-463f-af87-ea22eb3efa0c.png)

**Comment by FALSkills** [comment]
I'll update it sometime this weekend, probably tomorrow morning.

**Comment by FALSkills** [comment]
Can you confirm that the shortcut/ladder has no requirements?  I couldn't find any on the wiki

**Comment by FALSkills** [comment]
I added both handholds to the web, one into the lizardman canyon and one into the lizardman shamans canyon.  They will require NavigationSpecialCases as defined here:
962ba3f1671b3edb0d9af98452747ad6d7ad9f2c

They should be live the next time dax deploys, usually within a day depending on availability.
