### ISSUE TITLE
Boat to Slepe Missing

### ISSUE THREAD

**Issue by SkrrtNick** [itsdax/Runescape-Web-Walker-Engine#112]
![image](https://user-images.githubusercontent.com/79165336/156936475-016eee5c-707c-47ac-9270-94e471d7ae77.png)
Tile: 3672, 3542, 0
Can right click "Travel" on the NPC Andras (10,000 if the boat is not unlocked - free if it is). Can also right click "Travel" on the row boat

Takes you to here:
![image](https://user-images.githubusercontent.com/79165336/156936596-a5fbce74-73bc-4ee2-873d-1b137c44e641.png)

Tile: 3661, 3277, 0

**Comment by SkrrtNick** [comment]
I believe the varbit for travel is 10150

**Comment by SkrrtNick** [comment]
On closer inspection the boat north of the ectophial isn't mapped

**Comment by FALSkills** [comment]
This has been added to the walker engine, and will be available on the back-end after the next release.  I'll notify dax later today after I work on a few other issues.
