### ISSUE TITLE
Teleport.java should not have state

### ISSUE THREAD

**Issue by itsdax** [itsdax/Runescape-Web-Walker-Engine#118]
`src/main/java/dax/teleports/Teleport.java` holds mainly an enum. Enums shouldn't have state.

`failedAttempts` should be moved into the caller's responsibility to retry.

**Comment by FALSkills** [comment]
@itsdax to clarify, do you propose that the failedAttempts be removed altogether or that there is no "reset" of the failedAttempts variable?

**Comment by Zetta-Zerena** [comment]
Huh?

**Comment by itsdax** [comment]
`failedAttempts` should be removed and the retry mechanism should be in the calling code.

**Comment by FALSkills** [comment]
I will remove it, but this mechanic is a safeguard for items such as diary rewards which may have a limited number of teleports per day and no accessible way of knowing when they are usable.

**Comment by itsdax** [comment]
Sounds good. We still want to keep that mechanism, but it needs to be handled in the script's code instead of library.

**Comment by SkrrtNick** [comment]
Unsure how this is progressing but this issue is making the walker walk paths that it really shouldn’t be and causing large unnecessary paths to be traversed

**Comment by FALSkills** [comment]
> 

This is not going to be causing that, other errors in your script logic are the only thing that would lead to that.  Once this walker issue is resolved, the problem will likely become evident in your script workflow because the walker will not fix itself by defaulting to a walkable path, and will instead fail to use a teleport method endlessly.

**Comment by FALSkills** [comment]
My best guess for the causes would be some interface blocking teleport methods from being used, such as the bank or grand exchange windows, but if the issue persists then we may need to do more investigating

**Comment by SkrrtNick** [comment]
> My best guess for the causes would be some interface blocking teleport methods from being used, such as the bank or grand exchange windows, but if the issue persists then we may need to do more investigating

I thought dax walker closed interfaces before attempting to walk a path?

Anyways, I added some checks for GE and Bank interfaces and same results, it's pretty consistent after 3-5 hours of runtime

**Comment by rokaHakor** [comment]
Are there any recommendations on how to do the script side tracking for diary teleport charges/attempts?
