### ISSUE TITLE
North revenant cave exit bug

### ISSUE THREAD

**Issue by Slimers1** [itsdax/Runescape-Web-Walker-Engine#120]
Hey

Due to the new update, the exit is not where it used to be. Could you have a look?

**Comment by scriptoboy** [comment]
How is the remap coming? Can you give us an ETA? not trying to push you, just informing :)!

**Comment by FALSkills** [comment]
It should be live, let me know if there are any lingering issues.

**Comment by scriptoboy** [comment]
My issues at the south entrance seem to be fixed. Thanks a lot!
