### ISSUE TITLE
GlobalWalking Ferox to Revs issue: Already has path, but can't locate position on the path

### ISSUE THREAD

**Issue by scriptoboy** [itsdax/Runescape-Web-Walker-Engine#121]
Hey,

So I have a GlobalWalking function that moves from Ferox Enclave to the Revenant caves. It properly handles the barrier at Ferox Enclave, and also handles the dialogue for the 100K fee at the entrance. When it has entered the cave, I have another GlobalWalking function that moves to specific locations within the cave. However, it will freeze for about 10 seconds at the entrance before actually moving onto the path.

`[12:05:14] PathAnalyzer attempt to find closest tile in path: null [(3128, 3629, 0), (3127, 3629, 0), (3126, 3629, 0), (3125, 3629, 0), (3124, 3629, 0), (3123, 3629, 0), (3122, 3629, 0), (3121, 3629, 0), (3120, 3629, 0), (3119, 3629, 0), (3118, 3629, 0), (3117, 3629, 0), (3116, 3629, 0), (3115, 3629, 0), (3114, 3629, 0), (3113, 3629, 0), (3112, 3629, 0), (3111, 3629, 0), (3110, 3629, 0), (3109, 3629, 0), (3108, 3629, 0), (3107, 3629, 0), (3106, 3629, 0), (3105, 3629, 0), (3104, 3629, 0), (3103, 3629, 0), (3102, 3629, 0), (3101, 3630, 0), (3100, 3631, 0), (3099, 3632, 0), (3098, 3633, 0), (3097, 3634, 0), (3096, 3635, 0), (3095, 3636, 0), (3094, 3637, 0), (3093, 3638, 0), (3092, 3639, 0), (3091, 3640, 0), (3090, 3641, 0), (3089, 3642, 0), (3088, 3643, 0), (3087, 3644, 0), (3086, 3645, 0), (3085, 3646, 0), (3084, 3647, 0), (3083, 3648, 0), (3082, 3649, 0), (3081, 3649, 0), (3080, 3649, 0), (3079, 3649, 0), (3078, 3649, 0), (3078, 3650, 0), (3077, 3651, 0), (3076, 3651, 0), (3075, 3652, 0), (3075, 3653, 0), (3196, 10056, 0)]`

It prints this about 20 times before actually moving on. I added the full debug as an attachment. Nothing change in my code logic, and this started happening since about 1-2 weeks, and also happens every time for every instance running.

[dax_revs_error.txt](https://github.com/itsdax/Runescape-Web-Walker-Engine/files/8520649/dax_revs_error.txt)

**Comment by FALSkills** [comment]
Closed as duplicated to #120
