### ISSUE TITLE
Walking to the fence to get into the MM2 caves doesn't generate a path

### ISSUE THREAD

**Issue by SkrrtNick** [itsdax/Runescape-Web-Walker-Engine#122]
![image](https://user-images.githubusercontent.com/79165336/167266357-cf6bdd0f-f238-42aa-9d37-f9e6cde39d94.png)

Once you walk beyond the fence, a path is able to be generated just fine.

Object name is "Opening" and the action is "Pass-through"

**Comment by FALSkills** [comment]
Path was live on the backend but the walker was missing the required varbit, fixed here 546c0c22832c6397e86868d94e082e14498aa760
