### ISSUE TITLE
Add minigame/home teleports

### ISSUE THREAD

**Issue by Naton1** [itsdax/Runescape-Web-Walker-Engine#124]
This was previously thought to not be possible but now a game setting is available. 

If anyone else wants to pick it up go for it.

Game setting 892 is the minutes between the last time the teleport was used and 'epoch'
Game setting 888 is the same, but for minigame teleports

Ex.
`boolean canHomeTeleport = Game.getSetting(892) * 60 * 1000 + 30 * 1000 < System.currentTimeMillis()`
The 30 * 1000 is the time for the spell to come off cooldown, and the 60 * 1000 converts the minutes to milliseconds.

**Comment by Naton1** [comment]
> Hey @Naton1, just wanted to confirm that the example calculation should use: `boolean canHomeTeleport = (Game.getSetting(892) * 60 * 1000) + (30 * 1000 * 60) < System.currentTimeMillis()`
> 
> because we would need to convert the second number to millis as well

Yeah you’re right

**Comment by FALSkills** [comment]
Added in be747de6964c38b6b0e3977d7b079a4bd249086b and 77ca8fb9f2308c465aa8aacb93df2d72b57f372a but will require additional updates
