### ISSUE TITLE
Collisionflags

### ISSUE THREAD

**Issue by LostVirt** [itsdax/Runescape-Web-Walker-Engine#125]
Currently its not checking for blocking floor decorations, so dax is generating paths that can't be traversed.
This is true for both Web-Walker-Engine and the Path Generator on the server.

### Fix Example:
```java
public static final int BLOCK_OBJECT = 0x100;
public static final int BLOCK_FLOOR_DECORATION = 0x40000;
public static final int BLOCK_FLOOR = 0x200000;

public static final int BLOCK_FULL = BLOCK_OBJECT | BLOCK_FLOOR_DECORATION  | BLOCK_FLOOR;
```

Check validity:
```java
// isValid(flag, BLOCK_FULL)
public static boolean isValid(int flag, int checkFlag)
{
    return (checkFlag & flag) != 0;
}
```

### Current Collision Flags:
![CurrentCollisionFlags](https://user-images.githubusercontent.com/54107113/168558912-21bd4569-7057-426f-abdb-68ea6b53028a.png)

**Generates Invalid Path:**
![Invalid Path](https://user-images.githubusercontent.com/54107113/168554035-7744138d-feb3-408a-8bf5-17c575d922cf.png)

### Fixed Collision Flags:
![FixedCollisionFlags](https://user-images.githubusercontent.com/54107113/168554422-b98372cc-a0b4-4b84-82ba-405692a5f244.png)

**Generates Valid Path:**
![Valid Path](https://user-images.githubusercontent.com/54107113/168556805-f8307fba-8821-4167-b963-4d7ecd1eaad3.png)

**Comment by FALSkills** [comment]
I took a quick look and the collision generator was still not generating a blocked tile there, so I'm going to have to take a deeper look at that but I figured I'd add a fix in the meantime.  The path generator should treat that route as blocked after the next deployment cycle.

**Comment by FALSkills** [comment]
Added in 4b3b51f
