### ISSUE TITLE
Closest tile in path is not in minimap

### ISSUE THREAD

**Issue by GeniuSKilleR95** [itsdax/Runescape-Web-Walker-Engine#129]
it keep failing without getting new tile 
https://pastebin.com/sWPD22KD

**Comment by FALSkills** [comment]
Can you please provide screenshots of the game so we can see things like if the map chunk is not loaded etc

**Comment by GeniuSKilleR95** [comment]
![image](https://user-images.githubusercontent.com/54787216/170894802-9d0d61d5-5530-4ac1-abf8-fa7a4ca9b7a2.png)

**Comment by FALSkills** [comment]
Fixed here 5435d8197300496b557f12550fc9dc9833148503
