### ISSUE TITLE
Issue with pathing/Crevice at Revenant Caves

### ISSUE THREAD

**Issue by scriptoboy** [itsdax/Runescape-Web-Walker-Engine#132]
For some reason, when using Daxwalker in the Revenant caves using the south entrance, bots will occasionaly end up in level 28 wilderness at the Crevice (where you can jump down into the cave). Unfortunately, nothing happens as Daxwalker does not seem to be able to interact with this crevice. I still can't understand how they end up there, as pathing using the south entrace from where I call GlobalWalking (Ferox Enclave) is a much more optimal route. Any ideas on improving the pathing and/or implementing handling the crevice?

**Comment by FALSkills** [comment]
If you can provide screenshots or detailed information on what is happening (and where specifically on the map, either with tile coordinates or screenshots of the map) I can work on this.

**Comment by FALSkills** [comment]
I remapped the southern and northern exits of the rev caves today, should be live later today.
