### ISSUE TITLE
Minigame teleport issues

### ISSUE THREAD

**Issue by FALSkills** [itsdax/Runescape-Web-Walker-Engine#134]
Please list any known issues with minigame or home teleports so that I can track and fix them all in one place.  Currently the only one I am aware of is the death tile, if anyone has an effective way of determining that we are on a "death tile" then let me know, otherwise a fix will be attempted upon failure to teleport.

**Comment by itsdax** [comment]
Below are 2 cases:

- Using from a location you can't use: 
![image](https://user-images.githubusercontent.com/8293051/173008509-78a7cc85-9cdf-441e-9c83-6355bf7c868c.png)

- Using from death tile or when your character is running
![Screen Shot 2022-06-10 at 2 57 57 AM](https://user-images.githubusercontent.com/8293051/173008563-818b6955-aa35-404b-9df7-67de1abd4a4c.png)

**Comment by FALSkills** [comment]
@itsdax do you have any details you can provide for that first case? there are going to be areas to blacklist

**Comment by GeniuSKilleR95** [comment]
home teleport sometimes dont work at death tile too
