### ISSUE TITLE
Add fossil island volcano bank to walkToBank()

### ISSUE THREAD

**Issue by Naton1** [itsdax/Runescape-Web-Walker-Engine#139]
Screenshot from a user who wants it
![image](https://user-images.githubusercontent.com/28943608/175792727-0ca34b8f-8c14-4ca1-9b47-299f18e81676.png)

**Comment by FALSkills** [comment]
Added to walker engine ed6cc74247b8006abe5e304c17ba4d4ed09a9539
Bank will need to be added to backend @itsdax, it's ready whenever you want to deploy.
