### ISSUE TITLE
Giants Foundry unmapped

### ISSUE THREAD

**Issue by SkrrtNick** [itsdax/Runescape-Web-Walker-Engine#146]
New location near Al Kharid:
![image](https://user-images.githubusercontent.com/79165336/179270576-63822e3e-be3e-4e8d-b51f-ab13894dcc45.png)

Accessible directly by the Giants Foundry minigame teleport if Sleeping Giants is completed

**Comment by FALSkills** [comment]
Should be added in next update, however the minigame teleport will be added at a later date as I don't see the minigame accessible from the tribot sdk.

**Comment by SkrrtNick** [comment]
Yeah it's been sitting in a PR. Thanks Fals - shall I reopen whenever it is they merge?

**Comment by SkrrtNick** [comment]
Update is now live with the minimap teleport in it @FALSkills

**Comment by FALSkills** [comment]
Added daa97fa
