### ISSUE TITLE
Skills necklace teleport  is not working if it's in  the inventory.

### ISSUE THREAD

**Issue by Shardzx** [itsdax/Runescape-Web-Walker-Engine#148]
Daxwalker correctly uses the item teleport if it's worn. However if the item is  in the inventory. it just rubs the skill necklace. And then it closes the interface and decides to walk without teleporting.

**Comment by FALSkills** [comment]
I just tested using the skills necklace to the farming guild and it worked from the inventory without issue.  Are you running a local version of daxwalker?  If so, you need to update your library.

**Comment by Shardzx** [comment]
I was using the Daxwalker movements task with nRestocker.  This has happened for a month (when i started using it).
 Could it be, that it is an script issue?
What is happening:
https://pastebin.com/sS2Eyihe
https://imgur.com/a/5J48uEL

**Comment by FALSkills** [comment]
This is a script issue, the script is on a much older iteration of daxwalker.  You'll have to ask Naton to pick out the methods here to fix it:
https://github.com/itsdax/Runescape-Web-Walker-Engine/blob/02f8e6a7d4217f12ecc5e874b8c79d8ff3ede38a/src/main/java/dax/teleports/Teleport.java#L901
