### ISSUE TITLE
tile need to be added 

### ISSUE THREAD

**Issue by GeniuSKilleR95** [itsdax/Runescape-Web-Walker-Engine#151]
![image](https://user-images.githubusercontent.com/54787216/182500889-80b9f5bb-18d9-4c0c-a998-510dd732f4df.png)

![image](https://user-images.githubusercontent.com/54787216/182500910-921eb2d8-b367-4fe0-8aa0-37aa6e3da78f.png)

**Comment by FALSkills** [comment]
Tile will be added in next deployment on the backend
