### ISSUE TITLE
musa point -> brimhaven 

### ISSUE THREAD

**Issue by GeniuSKilleR95** [itsdax/Runescape-Web-Walker-Engine#154]
currently i am unable to use musa point ship directly to brimhaven 

the path is generated to port phasmatys first then redirect to brimhaven when we can just charter to brimhaven 

`Position[] path = {
    new Position(2954, 3158, 0),
    new Position(2954, 3158, 0),
    new Position(2954, 3157, 0),
    new Position(2954, 3156, 0),
    new Position(2954, 3155, 0),
    new Position(2954, 3154, 0),
    new Position(2954, 3153, 0),
    new Position(2954, 3152, 0),
    new Position(2954, 3151, 0),
    new Position(2954, 3150, 0),
    new Position(2954, 3149, 0),
    new Position(2954, 3148, 0),
    new Position(2954, 3147, 0),
    new Position(2953, 3146, 0),
    new Position(3702, 3503, 0),
    new Position(2760, 3237, 0),
    new Position(2760, 3236, 0),
    new Position(2760, 3235, 0),
    new Position(2760, 3234, 0),
    new Position(2760, 3233, 0),
    new Position(2760, 3232, 0),
    new Position(2760, 3231, 0),
    new Position(2760, 3230, 0),
    new Position(2760, 3229, 0),
    new Position(2761, 3228, 0),
    new Position(2761, 3227, 0),
    new Position(2762, 3227, 0),
    new Position(2763, 3227, 0),
    new Position(2764, 3227, 0),
    new Position(2765, 3227, 0),
    new Position(2766, 3227, 0),
    new Position(2767, 3227, 0),
    new Position(2768, 3227, 0),
    new Position(2769, 3227, 0),
    new Position(2770, 3227, 0),
    new Position(2771, 3227, 0),
    new Position(2772, 3228, 0),
    new Position(2772, 3229, 0),
    new Position(2772, 3230, 0),
    new Position(2771, 3230, 0)
};`

**Comment by FALSkills** [comment]
Can you please provide specifics from in-game?  What are the requirements for that route, including settings/varbits or item requirements, such as a specific number of coins.  Is the route two-way, and if so does it have the same costs going either way?

**Comment by GeniuSKilleR95** [comment]
dont think there is requirements for it 
it is two-way route yea
gold needed is 200 coins to go from musa point to brimhaven
gold needed is 480 coins to go from brimhaven to musa point

**Comment by FALSkills** [comment]
Thanks - I think we need to add a members requirement for musa pt to brimhaven as well.  These will be added next release, and I don't think there is any work to add it to the walker engine so that's nice!
