### ISSUE TITLE
Getting stuck at falador park

### ISSUE THREAD

**Issue by SkrrtNick** [itsdax/Runescape-Web-Walker-Engine#155]
Generating path: {"player":{"attack":-1,"defence":-1,"strength":-1,"hitpoints":-1,"ranged":-1,"prayer":-1,"magic":-1,"cooking":-1,"woodcutting":-1,"fletching":-1,"fishing":-1,"firemaking":-1,"crafting":-1,"smithing":-1,"mining":-1,"herblore":-1,"agility":-1,"thieving":-1,"slayer":-1,"farming":-1,"runecrafting":-1,"hunter":-1,"construction":-1,"setting":[{"key":10,"value":0},{"key":11,"value":0},{"key":17,"value":14},{"key":32,"value":0},{"key":63,"value":0},{"key":68,"value":16},{"key":71,"value":0},{"key":101,"value":28},{"key":111,"value":9},{"key":116,"value":0},{"key":131,"value":0},{"key":144,"value":0},{"key":145,"value":0},{"key":150,"value":0},{"key":165,"value":30},{"key":176,"value":0},{"key":179,"value":0},{"key":212,"value":0},{"key":273,"value":0},{"key":299,"value":0},{"key":302,"value":61},{"key":307,"value":110},{"key":314,"value":0},{"key":335,"value":0},{"key":347,"value":0},{"key":351,"value":0},{"key":365,"value":0},{"key":371,"value":0},{"key":387,"value":0},{"key":399,"value":0},{"key":425,"value":0},{"key":437,"value":0},{"key":440,"value":0},{"key":482,"value":0},{"key":622,"value":0},{"key":655,"value":0},{"key":671,"value":0},{"key":705,"value":0},{"key":794,"value":0},{"key":810,"value":33554432},{"key":869,"value":0},{"key":896,"value":0},{"key":964,"value":0},{"key":970,"value":0},{"key":1630,"value":0},{"key":1671,"value":459},{"key":1672,"value":16384}],"varbit":[{"key":192,"value":0},{"key":199,"value":0},{"key":357,"value":11},{"key":2310,"value":0},{"key":2328,"value":0},{"key":3534,"value":0},{"key":3618,"value":0},{"key":3741,"value":0},{"key":4494,"value":0},{"key":4538,"value":0},{"key":4566,"value":0},{"key":4885,"value":0},{"key":4895,"value":300},{"key":4897,"value":1},{"key":5027,"value":0},{"key":5087,"value":0},{"key":5088,"value":0},{"key":5089,"value":0},{"key":5090,"value":0},{"key":5800,"value":0},{"key":5810,"value":0},{"key":6104,"value":0},{"key":7255,"value":0},{"key":9016,"value":0},{"key":10150,"value":0},{"key":13903,"value":0}],"member":true,"equipment":[{"key":1506,"value":1},{"key":1275,"value":1}],"inventory":[{"key":11986,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":960,"value":1},{"key":1539,"value":161},{"key":2347,"value":1}]},"requests":[{"start":{"x":3161,"y":3478,"z":0},"end":{"x":1816,"y":3726,"z":0}},{"start":{"x":2994,"y":3377,"z":0},"end":{"x":1816,"y":3726,"z":0}},{"start":{"x":3225,"y":3219,"z":0},"end":{"x":1816,"y":3726,"z":0}},{"start":{"x":3162,"y":3488,"z":0},"end":{"x":1816,"y":3726,"z":0}}]}

Using a ROW from GE to port piscarilius the script will teleport to falador and then get stuck and sit in falador park:
![image](https://user-images.githubusercontent.com/79165336/187509267-966933bb-2fdf-4829-b563-f3fe90265646.png)

**Comment by FALSkills** [comment]
Do you have any additional logs?  I'm guessing it is due to collision but usually we can tell from the debugs

**Comment by SkrrtNick** [comment]
I don't - I will see if I can get the user to provide them.

Thanks Fal

**Comment by FALSkills** [comment]
I re-did collision here just in case, but I'm not sure what else to do for now.  Closing this issue.

**Comment by SkrrtNick** [comment]
Hi @FALSkills path generation is no longer working for near the falador park since this update

![image](https://user-images.githubusercontent.com/79165336/194938605-b6ffc201-1051-4cac-ad1d-0e28c54e3629.png)
![image](https://user-images.githubusercontent.com/79165336/194938630-9ee5662a-08ca-4753-bbeb-e8d5c0ccee8a.png)
