### ISSUE TITLE
Wilderness slayer cave - no web path found

### ISSUE THREAD

**Issue by Naton1** [itsdax/Runescape-Web-Walker-Engine#156]
I have a user who's unable to path in the wilderness slayer cave - "start":{"z":0,"y":10120,"x":3397},"end":{"z":0,"y":3497,"x":3094} is giving {"pathStatus":"NO_WEB_PATH","path":[],"cost":0}

![image](https://user-images.githubusercontent.com/28943608/194128243-9a934799-7892-45aa-9686-90c40a8fa308.png)

**Comment by FALSkills** [comment]
Collision has been remapped in the wilderness slayer cave, this should be resolved with next deployment.
