### ISSUE TITLE
Doom handler 

### ISSUE THREAD

**Issue by GeniuSKilleR95** [itsdax/Runescape-Web-Walker-Engine#169]
if the path is generated while the doom is open interface ( 560 ) in my case and it need to handle object ( stairs, door , etc ) it will ignore the doom and try interact with the object through the interface

**Comment by FALSkills** [comment]
Hey @GeniuSKilleR95, just wondering, are you running a local daxwalker library or the remote one? If local, can you try adding a line here and let me know if that fixes it:
https://github.com/itsdax/Runescape-Web-Walker-Engine/blob/8c66e25343fb1dde6565ca59d912860756c7da61/src/main/java/dax/walker_engine/interaction_handling/PathObjectHandler.java#L392

The line to add:
`DoomsToggle.handleToggle()`
