### ISSUE TITLE
Add temple first and second floor support

### ISSUE THREAD

**Issue by jens4626** [itsdax/Runescape-Web-Walker-Engine#175]
The temple during Priest in Peril is not supported as of now.

(3412, 3489, 1) and (3412, 3489, 2)

Must be able to handle the cell door on second floor and stairs on first floor

**Comment by FALSkills** [comment]
Added, should be live in next deploy (usually within 1-2 days)

Note: the door on floor 2 has no handler built in; you are not able to walk through it until you have progressed far enough through Priest in Peril, but the path generator does not know that.  Make sure you have progressed far enough and unlocked the door.
