### ISSUE TITLE
When traveling to bank, prioritize Ring of dueling over Amulet of glory teleport

### ISSUE THREAD

**Issue by Tyler-V** [itsdax/Runescape-Web-Walker-Engine#18]
If you have both items on your person, we should prioritize the cheapest / easiest renewable source of travel first.

**Comment by FALSkills** [comment]
I don't think it will use those banks unless they are close to the position of the character when the path to bank is generated.

**Comment by Tyler-V** [comment]
Currently I have to hack in walking below 20 wilderness and firing ring of dueling teleport manually, then calling walk to bank. Calling it above or below 20 wilderness will still result in a amulet of glory teleport if its in the inventory.

Maybe we can add another method that takes TeleportMethod as a variable.

WebWalker#walkToBank(WalkingCondition walkingCondition, TeleportMethod teleportMethod)

**Comment by FALSkills** [comment]
You could blacklist the glory teleport in the TeleportManager, but regardless it will still be extra steps.
I don't think the walker supports wilderness teleporting too well, if you are above the teleport limit then it will not walk to the limit and teleport, it will walk the whole way.

**Comment by Tyler-V** [comment]
Something like that is manageable I think though and probably adds too much complexity for the library.

I'm using something like this it works fine for now:

```
				if (Wilderness.getLevel() <= 20) {
					return Walking.travel(CASTLE_WARS_BANK);
				}
				else {
					WalkingCondition canTeleport = new WalkingCondition() {
						public State action() {
							if (Wilderness.getLevel() <= 20) {
								return State.EXIT_OUT_WALKER_SUCCESS;
							}
							return State.CONTINUE_WALKER;
						}
					};
					return Walking.travel(new RSTile(Player.getPosition()
							.getX(), 3650, 0), canTeleport);
				}
```
