### ISSUE TITLE
shilo village cart system

### ISSUE THREAD

**Issue by GeniuSKilleR95** [itsdax/Runescape-Web-Walker-Engine#180]
![image](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/54787216/1eee66c6-5dc5-4350-a079-05411c67d2f4)

**Comment by FALSkills** [comment]
> For a fee varying from 10 to 200 [coins](https://oldschool.runescape.wiki/w/Coins), players can travel between northern [Brimhaven](https://oldschool.runescape.wiki/w/Brimhaven), where [Hajedy](https://oldschool.runescape.wiki/w/Hajedy) runs the service, and near the [Shilo Village](https://oldschool.runescape.wiki/w/Shilo_Village_(location)) bank, where [Vigroy](https://oldschool.runescape.wiki/w/Vigroy) runs the service. The fee is proportionate to the amount of coins the player has in their inventory.
> 
> The right-click "Pay-fare" option always costs 200 coins, no matter how much is in the player's inventory.

kinda funny it costs more depending on how much gp you have lol.  i will default it to 200gp

**Comment by FALSkills** [comment]
added here https://github.com/itsdax/Runescape-Web-Walker-Engine/commit/5f1c3ad9318b5894dbbfc5ad4c1322cbee0b31e6
