### ISSUE TITLE
port phasmatys

### ISSUE THREAD

**Issue by GeniuSKilleR95** [itsdax/Runescape-Web-Walker-Engine#184]
https://pastebin.com/YDBdhZzS

trying to use ship to prifddinas instead of port phasmatys -> only when song of the elves quest is done and we want to go to port phasmatys

**Comment by FALSkills** [comment]
Can you please provide more context or provide a full description of what is happening?  The issue you are describing does not match the issue that the logs are showing.  The path requires 5,200 gp and you only have 2,650.  I will adjust the cost to travel to Prifddinas.

**Comment by FALSkills** [comment]
Should be resolved lmk
