### ISSUE TITLE
cant walk when the plough blocking the way cause it takes like 4-5 tiles 

### ISSUE THREAD

**Issue by GeniuSKilleR95** [itsdax/Runescape-Web-Walker-Engine#185]
https://pastebin.com/ZtdxDQgJ

![image](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/54787216/bfaae3b2-69c4-4663-90a2-9e55cc6fbbe0)

**Comment by FALSkills** [comment]
Potentially fixed in this commit https://github.com/itsdax/Runescape-Web-Walker-Engine/commit/8221356932d790c8382871b1c4054813fb22f9c9

**Comment by GeniuSKilleR95** [comment]
> Potentially fixed in this commit [8221356](https://github.com/itsdax/Runescape-Web-Walker-Engine/commit/8221356932d790c8382871b1c4054813fb22f9c9)

that didnt fix it

**Comment by FALSkills** [comment]
will debug this in depth once i get a chance
