### ISSUE TITLE
Fossil island wyvern cave support

### ISSUE THREAD

**Issue by Shardzx** [itsdax/Runescape-Web-Walker-Engine#187]
Entrance
<img width="686" alt="AnyDesk_lzHeFJiD0P" src="https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/69726907/61856fd4-7552-4891-9dd0-c5c3f63930e9">

Exit
![image](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/69726907/820dbb24-45e6-4a74-9c2f-74fbf9b2d905)

Stairs down
![image](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/69726907/cea27652-1de6-42d0-a86f-b914eab4693b)

Stairs up
![image](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/69726907/0aede25f-0488-4f5d-a845-0d0268e42dc8)

https://pastebin.com/rpDamuqN

**Comment by FALSkills** [comment]
Hello, 
So sorry for the delay in getting back to you.  This area is already supported - the issue you are having is that you are walking to a blocked tile which is east of where you drop down.  
The tile that you are walking to:

> "end":{"z":0,"y":10294,"x":3592}

Server response:

> [DaxWalker] Server response: {"pathStatus":"BLOCKED_END","path":[],"cost":0}

If that sounds incorrect and that tile is actually walkable, let me know and I'll re-map the area.
