### ISSUE TITLE
canUseMinigameTeleport NPE when not logged in

### ISSUE THREAD

**Issue by SkrrtNick** [itsdax/Runescape-Web-Walker-Engine#192]
Not sure if you care about NPEs prior to logging in

```java.lang.NullPointerException at dax.teleports.Teleport.canUseMinigameTeleport(Teleport.java:995)```

**Comment by FALSkills** [comment]
Probably just going to ignore because the DaxWalker library probably shouldn't be getting called before the game has initially loaded
