### ISSUE TITLE
Support for Xeric's Talismen teleport Xerics Heart

### ISSUE THREAD

**Issue by Rallik-Pog** [itsdax/Runescape-Web-Walker-Engine#207]
Request to add Xerics Heart teleport, only available if the player has completed Architectural Alliance miniquest.

New to this; saw other suggestions in issues, so posting this here. Let me know if there's anything I can do to help. (I have zero coding experience)

Feel free to delete this if this is the wrong place.

Thank you.

**Comment by SkrrtNick** [comment]
If you have no coding experience, you should ask whoever wrote the script you're using to contribute - should take less than 5 mins of their time

**Comment by FALSkills** [comment]
added cb3866bf45930628b5e29a0656510ad82180ef40
