### ISSUE TITLE
Path from fairyrings (BIQ) to Kalphite Cave

### ISSUE THREAD

**Issue by SlipperyPickle** [itsdax/Runescape-Web-Walker-Engine#210]
If you try to create a path between fairyring BIQ and the Kalphite cave it can't find a path. If you try to create the path from a tile next to the fairyring it does work. 

![image](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/11353209/926bd635-6094-427c-b727-d28ab1f216ba)

Failed to get path between (3251, 3095, 0) and (3323, 3121, 0) from Eternal Client.
Reason: 'undefined'

**Comment by SlipperyPickle** [comment]
Is it the same: as https://github.com/itsdax/Runescape-Web-Walker-Engine/issues/170

Since it does generate a path from a walkable tile next to the fairy rings.

**Comment by FALSkills** [comment]
Yes, that issue was resolved and I linked to the commit which fixed it.  Fairy ring tiles are blocked and need the client-side engine to handle that to keep the path generator working appropriately.
