### ISSUE TITLE
Suggestion - increase cost for teleports that take time to cast

### ISSUE THREAD

**Issue by SkrrtNick** [itsdax/Runescape-Web-Walker-Engine#212]
For example - lumby home teleport will get cast instead of walking from distances in which it would be faster to walk rather than sit and wait however many seconds the animation is.

Unsure of the tidiest way to implement

**Comment by FALSkills** [comment]
It's already implemented via the movecosts in the Teleports enum, you can adjust it with Teleport.LUMBRIDGE_HOME_TELEPORT.setMoveCost(value).  Its default is 150.  Other teleports are typically a movecost of 35.  Ideally this would be moved out of the Teleports enum and stored in a map object in the DaxWalker class, but I haven't made that change yet.
