### ISSUE TITLE
Trying to make use of Minecart system at Grand Exchange without it being unlocked.

### ISSUE THREAD

**Issue by scriptoboy** [itsdax/Runescape-Web-Walker-Engine#218]
I have had two different instances where Daxwalker would attempt to use the Minecart system at the Grand Exchange without having unlocked the system. It will loop, constantly trying to use the Minecart entrance, while the chat interface prompts an error. See the images below.

![minecart1](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/78447852/b39bf2c4-fb53-48cb-ade4-0386ddd2239f)
![minecart2](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/78447852/e2aa5b6f-7d18-4210-a5b5-531035249c0d)

**Comment by FALSkills** [comment]
Do you have script logs including the api request so that I can review it?  The requirements are properly configured on the server, as far as I can tell.

**Comment by FALSkills** [comment]
I suppose there is a chance that the user could have started The Giant Dwarf without actually taking the boat, but I'm not positive.  Regardless, there's a varbit that can be used to determine if Keldagrim is unlocked.  The varbit will need to get added client-side, and this will break the path for all other users until that varbit gets added.  This is a common route for Blast Furnace, so I don't want to break it for all users.  For that reason, I will add the varbit to the client-side but hold off on patching it server-side for the time being.  I would suggest to the user that they finish the first step of Giant Dwarf if they don't want to encounter this issue in the meantime.

**Comment by scriptoboy** [comment]
Unfortunately, I do not have script logs at this time. I believe this issue to be an edge case indeed, like you mentioned. Finishing the first step of Giant Dwarf indeed fixed the issue for now. Thanks for responding!
