### ISSUE TITLE
haunted woods tree

### ISSUE THREAD

**Issue by GeniuSKilleR95** [itsdax/Runescape-Web-Walker-Engine#222]
new WorldTile(3618, 3502, 0)

can we add this tree near this tile to ignore like the one in draynor manor it keep attacking us making us unable to walk

![image](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/54787216/780cbc78-fefd-47a1-a7bc-03265518c927)

**Comment by FALSkills** [comment]
Changes should be live later today, let me know if it's still happening tomorrow

**Comment by GeniuSKilleR95** [comment]
> Changes should be live later today, let me know if it's still happening tomorrow

this just happened again today

**Comment by FALSkills** [comment]
I further expanded the area back on Nov 6, let me know if it's still a problem.
