### ISSUE TITLE
MTA/Dueling arena

### ISSUE THREAD

**Issue by SickBrains** [itsdax/Runescape-Web-Walker-Engine#233]
![image](https://github.com/itsdax/Runescape-Web-Walker-Engine/assets/118488452/2942d7e1-2402-48da-8bad-ad9ed58f4a18)

When walking from varrock to MTA or dueling arena you can get stuck on this area which will continue to fail.

Position: (3344, 3291, 0)

[01:05:06] [Walker Engine] Failed attempt on action.
[01:05:08] [Walker Engine] PATH_DEBUG[ 3345, 3291, 0) -> OBJECT_BLOCKING -> (3346, 3291, 0) ]

If you want to go west it doesnt have the problem.

**Comment by FALSkills** [comment]
Updated, should be fixed later today
