### ISSUE TITLE
Request: Add Lithkren teleport under Digsite pendant

### ISSUE THREAD

**Issue by Naton1** [itsdax/Runescape-Web-Walker-Engine#247]
This is quicker than using digsite amulet to get here for banking purposes.

![image](https://github.com/user-attachments/assets/fb91bb11-f7c6-425c-b362-5bb850225e77)

"it chooses digsite even though i have lithkren unlocked. digsite is a continent away and requires another boat ride plus a few doors where as lithkren is 1 stair 1 door then there"

For context, requested by one of my customers using this in my fighting script.

**Comment by FALSkills** [comment]
Since teleports are all handled client-side, I can add these teleports and default them to be blacklisted.  The scripter would need to remove them from the blacklist when applicable

**Comment by FALSkills** [comment]
https://github.com/itsdax/Runescape-Web-Walker-Engine/commit/b384954695183cda652766c19953e6764221b7ef#diff-9d937b467f626e2aa70e6ade66c3a5746e8c3a947578fba41986700f5f1a88c0R51
https://github.com/itsdax/Runescape-Web-Walker-Engine/commit/1bc3e5ccc7022f48827d937a436514d332d70ce9

These should do it
