### ISSUE TITLE
Zeah collision is incorrect in the hosidius house

### ISSUE THREAD

**Issue by Naton1** [itsdax/Runescape-Web-Walker-Engine#34]
The web walker server is unable to generate a valid path to walk from the zeah port to sand crabs.
Here is a location where it gets stuck (might be some other spots in this area too, I would suggest re-obtaining collision for the whole area, if possible)
![image](https://user-images.githubusercontent.com/28943608/62010527-f862fd80-b139-11e9-9c14-0b6577309143.png)

**Comment by FALSkills** [comment]
Fixed, also mapped all of the upper levels of Hosidius
