### ISSUE TITLE
When in a f2p world at castle wars, dax walker tries to walk through members locations rather than take the door "teleport" back to clan wars

### ISSUE THREAD

**Issue by Naton1** [itsdax/Runescape-Web-Walker-Engine#35]
I am on a f2p world at castle wars, and generating a path anywhere in the game will attempt to walk out of the door and walk through the members areas. The mouse hovers the minimap as if its going to walk outside of the door. (looks like its missing a link from castle wars to clan wars on f2p worlds I think)
This can be recreated by going to castle wars on a f2p world and trying to walk anywhere
![image](https://user-images.githubusercontent.com/28943608/62010564-8b9c3300-b13a-11e9-8e4c-8d891a09db24.png)

**Comment by FALSkills** [comment]
Fixed
