### ISSUE TITLE
The area south of port phasmatys/locations added in with the theatre of blood are not mapped

### ISSUE THREAD

**Issue by Naton1** [itsdax/Runescape-Web-Walker-Engine#36]
The highlighted area is not supported 
ignore darkmeyer/meiyerditch, don't think those are useful in any way
![image](https://user-images.githubusercontent.com/28943608/62010604-edf53380-b13a-11e9-94fe-cc4fa00451b3.png)

**Comment by FALSkills** [comment]
Slepe and Raids 2 area should be added. Did collision in Meiyerditch as well but did not do any pathing - probably will not.

**Comment by FALSkills** [comment]
Added
