### ISSUE TITLE
Interacting with members gates in f2p results in infinite loop

### ISSUE THREAD

**Issue by Jachos** [itsdax/Runescape-Web-Walker-Engine#4]
If you walk outside of f2p on a f2p world (take the gate east of lumbermill for example,) the path handler will continuously interact with the members gate and report success, but not go anywhere. 

My ad-hoc solution was to make a specialObject within the PathObjectHandler class and fail handle() if the player is not in a member's world.

**Comment by itsdax** [comment]
How do you walk outside of a f2p zone in a f2p world?

**Comment by Jachos** [comment]
"if you send a walk request to walk outside of a f2p zone"

**Comment by itsdax** [comment]
I'm confused. You're asking about sending a walk request to a P2P area, while being in a F2P world. Is that correct?

**Comment by Jachos** [comment]
you're correct

**Comment by itsdax** [comment]
You'll need a breakout condition within the walker. Its not possible to go to a p2p area within a f2p world. Look into the walking conditions class.

**Comment by Jachos** [comment]
oh, that's a perfectly good solution. Thanks.
