### ISSUE TITLE
Falador Dwarven Mine entrance door at Position(3061, 3375,0) endlessly loops open/close

### ISSUE THREAD

**Issue by RSWrit3r** [itsdax/Runescape-Web-Walker-Engine#51]
Tried to path back into the dwarven mine after banking in Falador. It gets stuck endlessly opening/closing the door into the staircase house. 

This was literally my first day using daxWalker, so I don't know the code well enough to suggest a fix. 

A likely naive approach: It fixed it for me when I just took the "close" option out of PathObjectHandler() sortedOptions. That'll prob break other things though lol. 

Let me know if I'm just being dumb here, since I haven't had time to look into the code here yet. 

Edit: Btw no complaints on the actual functionality of this, it's way better than Tribot's default walking.

**Comment by RSWrit3r** [comment]
Conjecture after looking at it a bit: The current flow doesn't walk forward through the door after opening it, and since there is another blocking object (the stairs), it just assumes the object directly in front of it (the door) is causing the issue (Line 195 of PathObjectHandler), and closes it. Since the door is actually blocking it now, it opens the door, and .... infinite loop.

**Comment by FALSkills** [comment]
This has been fixed for a while in my fork: #50
