### ISSUE TITLE
Gets stuck on Karamja (f2p) if no coins

### ISSUE THREAD

**Issue by orange451** [itsdax/Runescape-Web-Walker-Engine#52]
I am trying to walk from Karamja to Draynor. Works fine unless I have no coins left when on Karamja. Ideally, DaxWalker should cast Lumbridge teleport. Can DaxWalker be extended with this functionality?

**Comment by FALSkills** [comment]
DaxWalker can't know if you have home teleport available.  You need to handle this yourself.

**Comment by itsdax** [comment]
i wonder if home teleport has a setting which the teleportmanager can check on

**Comment by FALSkills** [comment]
It does not, otherwise I would have implemented it.  It requires using the message listener which would require additional implementation on a per-script basis

**Comment by itsdax** [comment]
sounds good, closing issue
