### ISSUE TITLE
Make WalkerEngine method take List<RSTile> not ArrayList<RSTile>

### ISSUE THREAD

**Issue by orange451** [itsdax/Runescape-Web-Walker-Engine#54]
Would be useful if instead of ArrayList<RSTile>, the WalkerEngine walkPath methods accepted a List<RSTile>. This will let me easily convert a array of RSTiles (Returned from Tribot's Pathfinding class) to a list via: Arrays.asList(array)

Thanks!

**Comment by FALSkills** [comment]
This was changed a while back, closing issue.
