### ISSUE TITLE
Has trouble walking INTO Wizards tower

### ISSUE THREAD

**Issue by orange451** [itsdax/Runescape-Web-Walker-Engine#55]
WalkerEngine has some issues taking a path into the wizards tower (basement) when roofs are enabled. It keeps trying to click on a door through the tower when the player is outside. I could just turn roofs off, but this seems like something that could easily have a fallback method in the walker itself where it'd attempt to use the minimap if it can't click the object it's looking for?

**Comment by orange451** [comment]
Here's a screenshot displaying the issue
![image](https://user-images.githubusercontent.com/5247778/80759622-950d5e00-8b05-11ea-8b1b-d9a696ddf5db.png)

Instead of using the minimap to first navigate to the door, it attampts to click through the building nonstop

**Comment by orange451** [comment]
Also has trouble walking into mansion in varrok
![image](https://user-images.githubusercontent.com/5247778/81125430-1bf77780-8f06-11ea-8b50-d713f495851e.png)

Character is currently standing at the front door. It should really use minimap in these situations.

**Comment by itsdax** [comment]
the problem stems from tribot not supporting roofs enabled due to isClickable() methods breaking when it's enabled
anything under the roof will be returning true for isClickable
so tribot as a whole generally doesn't support roofs
i suggest to just turn roofs off
