### ISSUE TITLE
Cant walk anywhere from upstairs edgeville man house

### ISSUE THREAD

**Issue by orange451** [itsdax/Runescape-Web-Walker-Engine#58]
Hello, DaxWalker cant seem to generate a path if I am standing upstairs in edgeville man house:

![image](https://user-images.githubusercontent.com/5247778/81325578-90e1c300-9066-11ea-82a3-f1e3a4a0b63f.png)

I am just using a simple script that invokes DaxWalker.walkTo(RSTile). Doesn't seem to matter which tile I choose.

**Comment by FALSkills** [comment]
Added, will be live in next update.
