### ISSUE TITLE
Do you have a web API?

### ISSUE THREAD

**Issue by igoham** [itsdax/Runescape-Web-Walker-Engine#63]
Hi, Looking to leverage your work to contribute to the OSRS wiki. I wasn't able to find any documentation on the actual API endpoints, just docs on how to leverage from Tribot.

Is there any chance you have a web API exposed that I can send authenticated requests to, to get the details on a specific tile, for example the City that tile is in?

**Comment by itsdax** [comment]
yeah, all endpoints are just https requests but you'll have to look at how the client makes the requests and copy that. There aren't any docs on this since it wasn't intended to be used outside of a walker client. However, I don't have any problem with people using this for other purposes.
