### ISSUE TITLE
Adding first portion of Brine rat cave

### ISSUE THREAD

**Issue by David-Rodden** [itsdax/Runescape-Web-Walker-Engine#67]
The brine rat cavern is accessible just north of the keldagrim entrance
![image](https://user-images.githubusercontent.com/16359521/101995883-38207b80-3c82-11eb-976c-6c3e2eb3f08d.png)

Could this first past be mapped (before the obstacle) @FALSkills 
![image](https://user-images.githubusercontent.com/16359521/101995893-600fdf00-3c82-11eb-927b-c7652dc3e6cf.png)

**Comment by FALSkills** [comment]
Added 12/15, updates for engine are required.
