### ISSUE TITLE
Brimhaven top level

### ISSUE THREAD

**Issue by David-Rodden** [itsdax/Runescape-Web-Walker-Engine#68]
@FALSkills Brimhaven bottom level can link to an upper floor as shown here:
![Screenshot 2020-12-15 at 12 53 33 PM](https://user-images.githubusercontent.com/16359521/102271755-a2305f00-3ed4-11eb-8caa-f3eedd262b65.png)

Links accordingly to this area here, which is 2 levels higher:
![Screenshot 2020-12-15 at 12 53 57 PM](https://user-images.githubusercontent.com/16359521/102271758-a3618c00-3ed4-11eb-94d6-ef8b4eecc46c.png)

**Comment by FALSkills** [comment]
Will be added in next update.
