### ISSUE TITLE
Killerwatt Plane

### ISSUE THREAD

**Issue by David-Rodden** [itsdax/Runescape-Web-Walker-Engine#69]
@FALSkills Upon finishing Ernest the chicken you are able to access one plane through the top level of Draynor manor
Ernest the chicken varp id: 32, completion value: 3
![Screenshot 2020-12-15 at 1 08 50 PM](https://user-images.githubusercontent.com/16359521/102273311-fb998d80-3ed6-11eb-98e5-dbe263642354.png)

One can go through the portal again to leave the plane, back to the manor:
![killerwatt](https://user-images.githubusercontent.com/16359521/102273325-00f6d800-3ed7-11eb-8030-62e2110dc534.png)

**Comment by FALSkills** [comment]
I will add the connection for this, but there will likely be a chat option that needs to be handled for entering it the first time.  If you can provide that I will add it to the engine in the future.
