### ISSUE TITLE
Taverly Dungeon Upper Level

### ISSUE THREAD

**Issue by David-Rodden** [itsdax/Runescape-Web-Walker-Engine#70]
@FALSkills 
The Taverly dungeon has an upper level that can be accessed at three different points:
![image](https://user-images.githubusercontent.com/16359521/102286508-4e7e3f80-3eed-11eb-960f-938bea4c4ebe.png)

There are "Steps" to "Climb" to the left which will bring you to the upper level. The shortcut on the right is a pile of "Rocks" which you can "Jump-up" with, given you have 70 agility. And the rightmost one is another set of steps with no requirement.

**Comment by FALSkills** [comment]
Added, will be live in the next update.
