### ISSUE TITLE
Upper part of Edgeville Dungeon

### ISSUE THREAD

**Issue by David-Rodden** [itsdax/Runescape-Web-Walker-Engine#71]
@FALSkills 
The upper part of the Edgeville dungeon seems to not be mapped.
![image](https://user-images.githubusercontent.com/16359521/102287192-c6009e80-3eee-11eb-8f0e-b9ac7f21314b.png)
It is accessible at level 15 agility via monkeybars that lead to a small room.

**Comment by FALSkills** [comment]
I have added this to the web editor and tested the default path handler - it works but it probably needs a special case due to the monkey bars being a bit of a slower object to traverse.  I'll create a separate issue for that.
