### ISSUE TITLE
Path through Kebos Swamp goes through water?

### ISSUE THREAD

**Issue by David-Rodden** [itsdax/Runescape-Web-Walker-Engine#73]
@FALSkills There might have been an update of some kind that repositioned some of the elements near the Xeric's Shrine, but it seems to just generate a path that goes through the water here:
![image](https://user-images.githubusercontent.com/16359521/102746995-399e1380-4314-11eb-971d-eac5835125c8.png)

**Comment by FALSkills** [comment]
Remapped Kebos Swamp + Lowlands and fixed various paths
