### ISSUE TITLE
Gu'Tanoth missing mapping between gate and Ogre Enclave

### ISSUE THREAD

**Issue by David-Rodden** [itsdax/Runescape-Web-Walker-Engine#74]
@FALSkills Both the initial leadup to Gu'Tanoth and the Ogre Enclave are mapped; however, the short distance between the gate and the cave entrance seems to be missing.
The leadup to the gate is the current built path below, and the presumed path to the cave entrance would be in orange.
![image](https://user-images.githubusercontent.com/16359521/102747647-761e3f00-4315-11eb-9a72-d2994bd68e37.png)

**Comment by FALSkills** [comment]
Added these areas, they will require the Watchtower setting to be passed in the api request.  This setting (212) was just added to the walker engine today.  The first gate requires the setting to be 4 or higher, and the final gate requires the quest to be completed (14)
