### ISSUE TITLE
Meiyerditch laboratory mapping

### ISSUE THREAD

**Issue by David-Rodden** [itsdax/Runescape-Web-Walker-Engine#76]
There is a tunnel under Meiyerditch that leads to the blood altar as well as bloodvelds in two separate openings within the tunnel.
It is located around (3585, 9738, 0) @FALSkills 
![image](https://user-images.githubusercontent.com/16359521/105621461-68e4ec00-5dbc-11eb-8e87-b5f3ca9f4ec0.png)

**Comment by FALSkills** [comment]
I am going to add this area however I will not be adding the link from inside of the Meiyerditch laboratory, as that area is not exactly mapped and I don't plan on mapping the house navigation.  I will however add the entrance from the Myreque secret passageway.
