### ISSUE TITLE
Isle of Souls and respective dungeon on East coast

### ISSUE THREAD

**Issue by David-Rodden** [itsdax/Runescape-Web-Walker-Engine#77]
@FALSkills Isle of Souls has been added in-game and is accessible via the Edgeville portal. Map currently hasn't been updated but soul wars lobby now opens to the rest of the island.

Map below indicates with a red circle where the location of the accessible dungeon exists. There are no requirements to access any part of this island.

![image](https://user-images.githubusercontent.com/16359521/106813579-072b4a00-6626-11eb-8912-2c45e8a7758e.png)

**Comment by FALSkills** [comment]
Hi,
I have added the initial area but then realized it was a massive area to map lol.  I will try to get it all added this weekend.

**Comment by FALSkills** [comment]
Isle of Souls and connected dungeons should be mapped.
