### ISSUE TITLE
Unmapped? area: ardougne chaos druid tower

### ISSUE THREAD

**Issue by Marsunpaisti** [itsdax/Runescape-Web-Walker-Engine#80]
Hi. API is not giving me paths to ardougne chaos druids tower. I'm assuming the location is unmapped and people have been asking me about this. Door has a pick-lock option.

Tile just outside the door: 2565, 3356, 0
Tile just inside the door: 2564, 3356, 0

https://i.imgur.com/Dr6RX5u.png
https://i.imgur.com/r1BMOhm.png

**Comment by FALSkills** [comment]
This area is mapped, however it has the incorrect requirement of a lockpick.  I will remove that requirement and keep the 46 thieving requirement.  Update will be live next deployment, probably this weekend.
