### ISSUE TITLE
Unmapped? area: Asgarnian Ice Dungeon Skeletal wyverns 

### ISSUE THREAD

**Issue by Marsunpaisti** [itsdax/Runescape-Web-Walker-Engine#82]
My users are reporting that the walker isnt getting paths to the skeletal wyverns area. Is it unmapped?

**Comment by FALSkills** [comment]
The dungeon itself is mapped, but the connection between the rooms is not.  I can add a connection but I'll be adding a requirement to have one of the protective shields equipped.  I'll also look at adding a connection to the slayer-only room.

**Comment by FALSkills** [comment]
Area is mapped, it will be live next time that @itsdax deploys
